---
homebrew_taps:
  - homebrew/cask-fonts
  - espanso/espanso
  - mhoush/formulae
  - swift-psychrometrics/formula

homebrew_packages:
  - ansible
  - figlet
  - fzf
  - gh
  - git
  - git-lfs
  - go
  - httpie
  - hugo
  - jq
  - neovim
  - mas
  - psychrometrics
  - prettier
  - ripgrep
  - sourcekitten
  - swift-zet
  - tmux
  - vapor
  - zsh
  - zsh-async
  - zsh-completions

homebrew_casks:
  - arc
  - docker
  - espanso
  - keymapp
  - logi-options-plus
  - onyx
  - spacelauncher
  - wezterm
  - font-hack-nerd-font
  - font-inconsolata-nerd-font
  - font-jetbrains-mono-nerd-font

mas_apps:
  - { name: Amazon Kindle, id: 302584613 }
  - { name: Bakery, id: 1575220747 }
  - { name: pwSafe, id: 520993579 }
  - { name: Xcode, id: 497799835 }

