---
ansible_dotfiles_role_install_path: "~/.local/ansible/roles/ansible-role-dotfiles"

dockitems_remove:
  - Launchpad
  - TV
  - Podcasts
  - 'App Store'
  - Freeform
  - FaceTime
  - Contacts

dockitems_persist:
  - name: "Arc"
    path: "/Applications/Arc.app"
    pos: 2
  - name: "Calculator"
    path: "/Applications/Calculator.app"
  - name: "pwSafe"
    path: /Applications/pwSafe.app"
    pos: 3

homebrew_taps:
  - homebrew/cask-fonts
  - espanso/espanso
  - m-housh/formula
  - swift-psychrometrics/formula

# sourcekitten & vapor requires a full xcode to be installed, so we either need to do the
# mas section first, or install later.
homebrew_packages:
  - ansible
  - figlet
  - fzf
  - gh
  - git
  - git-lfs
  - go
  - httpie
  - hugo
  - jq
  - neovim
  - mas
  - psychrometrics
  - prettier
  - pure
  - ripgrep
  #- sourcekitten
  - swift-zet
  - tmux
  #- vapor
  - zsh
  - zsh-async
  - zsh-completions

homebrew_casks:
  - arc
  - docker
  - espanso
  - keymapp
  - logi-options-plus
  - onyx
  - spacelauncher
  - wezterm
  - font-hack-nerd-font
  - font-inconsolata-nerd-font
  - font-jetbrains-mono-nerd-font

mas_apps:
  - { name: Amazon Kindle, id: 302584613 }
  - { name: Bakery, id: 1575220747 }
  - { name: pwSafe, id: 520993579 }
  #- { name: Xcode, id: 497799835 }

