---
# Because I prefer to put ansible stuff in an `xdg_config_home` location, this
# will remove the default stuff once the playbook has ran.
remove_default_ansible_location: true
ansible_dotfiles_role_install_path: "~/.local/ansible/roles/m-housh.dotfiles"

homebrew_taps:
  #- homebrew/cask-fonts
  - espanso/espanso
  - m-housh/formula
  - swift-psychrometrics/formula

# sourcekitten & vapor requires a full xcode to be installed, so we either need to do the
# mas section first, or install later.
homebrew_packages:
  - ansible
  - figlet
  - fzf
  - gh
  - git
  - git-lfs
  - go
  - gopass
  - gpg2
  - gpg-tui
  - gum
  - hugo
  - jq
  - neovim
  - mas
  - psychrometrics
  - prettier
  - ripgrep
  - starship
  - swift-zet
  - tmux
  - zsh
  - zsh-async
  - zsh-completions

homebrew_casks:
  - arc
  - docker
  - espanso
  - keymapp
  - logi-options-plus
  - onyx
  - proton-drive
  - proton-mail
  - proton-pass
  - raycast
  - wezterm

homebrew_fonts:
  - font-hack-nerd-font
  - font-inconsolata-nerd-font
  - font-jetbrains-mono-nerd-font

# Un-comment Xcode when done testing, it takes forever to install.
mas_apps:
  - { name: Amazon Kindle, id: 302584613 }
  - { name: Bakery, id: 1575220747 }
  - { name: pwSafe, id: 520993579 }
  #- { name: Xcode, id: 497799835 }

dockitems_remove:
  - 'App Store'
  - Launchpad
  - Safari
  - Maps
  - FaceTime
  - Reminders
  - Freeform
  - TV
  - News

dockitems_persist:
  - name: Arc
    path: "/Applications/Arc.app"
    pos: 2
  - name: pwSafe
    path: "/Applications/pwSafe.app"
    pos: 3
  - name: WezTerm
    path: "/Applications/WezTerm.app"
    pos: 4
  - name: Calculator
    path: "/System/Applications/Calendar.app"
    pos: 5

launch_apps:
  #- "/Applications/Rectangle.app"
  #- "/Applications/SpaceLauncher.app"
  - "/Applications/Espanso.app"

projects_dir: "~/projects"
sites_dir: "{{ projects_dir }}/sites"
github_prefix: "https://github.com/m-housh"

# TODO: Add password-store repo, need to setup an authentication key / token.
repos:
  - repo: "{{ github_prefix }}/ansible-gen-playbook.git"
    dest: "{{ projects_dir}}/ansible/ansible-gen-playbook"
  - repo: "{{ github_prefix }}/mhoush.com.git"
    dest: "{{ sites_dir }}/mhoush.com"
  - repo: "{{ github_prefix }}/animalhouse.pro.git"
    dest: "{{ sites_dir }}/animalhouse.pro"
  - repo: "{{ github_prefix }}/hvachicks.com.git"
    dest: "{{ sites_dir }}/hvachicks.com"
  - repo: "{{ github_prefix }}/zets.git"
    dest: "{{ projects_dir }}/zets"

