---
- name: Ensure dotfiles role is installed.
  ansible.builtin.git:
    repo: "{{ dotfiles_role_repo }}"
    dest: "{{ ansible_dotfiles_role_install_path }}"
    version: "{{ ansible_dotfiles_role_repo_version }}"
    accept_hostkey: "{{ ansible_dotfiles_role_repo_accept_hostkey }}"
  become: false

- name: Check dotfiles role stat.
  stat:
    path: ~/.local/ansible/roles/ansible-role-dotfiles
  register: role_stat

- name: Move role to appropriate location.
  ansible.builtin.command: mv ~/.local/ansible/roles/ansible-role-dotfiles ~/.local/ansible/roles/m-housh.dotfiles
  when: role_stat.stat.exists

- name: Run dotfiles tasks.
  ansible.builtin.include_role:
    name: m-housh.dotfiles
