---
- name: Ensure mas-cli is installed.
  community.general.homebrew:
    name: mas
    state: present
  when: mas_apps | count > 0

- name: Get installed MAS apps
  ansible.builtin.command: mas list
  register: mas_list
  check_mode: false
  changed_when: false

- name: Ensure MAS apps
  ansible.builtin.command: mas install "{{ item.id | default(id) }}"
  loop: "{{ mas_apps }}"
  when: (item.id | default(item) | string) not in mas_list.stdout
