---

- name: Ensure taps
  community.general.homebrew_tap:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ homebrew_taps }}"
  when: homebrew_taps | default([]) | count > 0
  tags: taps

- name: Ensure cask Apps
  community.general.homebrew_cask:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    install_options: "{{ item.install_options | default(omit) }}"
    accept_external_apps: true
  loop: "{{ homebrew_casks }}"
  when: homebrew_casks | default([]) | count > 0
  tags: casks


- name: Ensure packages
  community.general.homebrew:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    install_options: "{{ item.install_options | default(omit) }}"
  loop: "{{ homebrew_packages }}"
  when: homebrew_packages | default([]) | count > 0
  tags: packages

- name: Fix permissions on the homebrew share directory.
  ansible.builtin.file:
    path: /opt/homebrew/share
    mode: '0775'
    state: present
    recurse: true
