---
- name: Restart Dock
  ansible.builtin.shell: killall Dock

- name: Restart UI Server
  ansible.builtin.shell: killall SystemUIServer

- name: Restart Finder
  ansible.builtin.shell: killall Finder

- name: Killall
  ansible.builtin.shell: killall {{ item }} &> /dev/null
  with_items:
    - "Finder"
    - "SystemUIServer"
    - "Dock"

