---
- name: Close any open system preferences panes.
  ansible.builtin.shell: osascript -e 'tell application "System Settings" to quit'

- name: Setup Dock.
  ansible.builtin.include_tasks: dock.yml
  tags: dock

- name: Setup Finder.
  include_tasks: finder.yml
  tags: finder

- name: Setup Desktop.
  ansible.builtin.include_tasks: desktop.yml
  tags: desktop

- name: Set screenshots location.
  block:
    - name: Ensure screenshot location exists.
      ansible.builtin.file:
        path: "{{ screenshots_location }}"
        state: directory

    - name: Set screenshots location.
      community.general.osx_defaults:
        domain: com.apple.screencapture
        key: location
        type: string
        value: "{{ screenshots_location }}"
      notify: "Restart UI Server"
  when: (screenshots_location.count | int) > 0
  tags: screenshots

# Keep this last, as it will use the `Killall` handler
- name: Setup globals.
  ansible.builtin.include_tasks: globals.yml
  tags: globals

